var searchData=
[
  ['_3a_0',[':',['..//github/workspace/api/README.md#autotoc_md20',1,'&lt;tt&gt;get_value&lt;/tt&gt;:'],['..//github/workspace/api/README.md#autotoc_md19',1,'&lt;tt&gt;set_value&lt;/tt&gt;:'],['..//github/workspace/ecosystem/sdk/resvault-sdk/README.md#autotoc_md2806',1,'Steps to scaffold a project using &lt;tt&gt;create-resilient-app&lt;/tt&gt;:']]],
  ['_3a_20committransaction_20tt_1',['&lt;tt&gt;postTransaction(data: PrepareAsset!): CommitTransaction&lt;/tt&gt;',['../d4/d98/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2docs_2GRAPHQL__SCHEMA__EXAMPLES.html#autotoc_md1219',1,'']]],
  ['_3a_20retrievetransaction_20tt_2',['&lt;tt&gt;getTransaction(id: ID!): RetrieveTransaction&lt;/tt&gt;',['../d4/d98/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2docs_2GRAPHQL__SCHEMA__EXAMPLES.html#autotoc_md1217',1,'']]],
  ['_3a_20string_20tt_3',['&lt;tt&gt;new ResVaultSDK(targetOrigin?: string)&lt;/tt&gt;',['..//github/workspace/ecosystem/sdk/resvault-sdk/README.md#autotoc_md2800',1,'']]],
  ['_3a_20strong_4',[': strong',['../d5/d62/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2NEXUS__TEST__INPUTS.html#autotoc_md1427',1,'&lt;strong&gt;Complete Queries (2, 9):&lt;/strong&gt;'],['../d7/d96/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2QUERY__TUTOR__EXAMPLES.html#autotoc_md1501',1,'&lt;strong&gt;Complete Queries (4):&lt;/strong&gt;'],['../d9/de8/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2TEST__DOCKER__SERVICES.html#autotoc_md1644',1,'&lt;strong&gt;Dockerized Services (docker-compose.dev.yml):&lt;/strong&gt;'],['../d9/d1a/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2TEAM__SETUP.html#autotoc_md1629',1,'&lt;strong&gt;Documentation Files (in GraphQ-LLM repository):&lt;/strong&gt;'],['../d9/de8/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2TEST__DOCKER__SERVICES.html#autotoc_md1645',1,'&lt;strong&gt;External Services (Not Dockerized in dev):&lt;/strong&gt;'],['../d9/d1a/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2TEAM__SETUP.html#autotoc_md1555',1,'&lt;strong&gt;Key Documentation Files (in GraphQ-LLM repository):&lt;/strong&gt;'],['../d7/d96/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2QUERY__TUTOR__EXAMPLES.html#autotoc_md1502',1,'&lt;strong&gt;Mutations (7, 8):&lt;/strong&gt;'],['../d9/d1a/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2TEAM__SETUP.html#autotoc_md1562',1,'&lt;strong&gt;Optional (for Nexus features):&lt;/strong&gt;'],['../d7/d96/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2QUERY__TUTOR__EXAMPLES.html#autotoc_md1492',1,'&lt;strong&gt;Queries (Copy these into the query editor):&lt;/strong&gt;'],['../d7/d96/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2QUERY__TUTOR__EXAMPLES.html#autotoc_md1493',1,'&lt;strong&gt;Questions (Copy these into the query editor):&lt;/strong&gt;'],['../d7/d96/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2QUERY__TUTOR__EXAMPLES.html#autotoc_md1500',1,'&lt;strong&gt;Simple Queries (1, 2, 3):&lt;/strong&gt;'],['../d5/d62/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2NEXUS__TEST__INPUTS.html#autotoc_md1426',1,'&lt;strong&gt;Simple Queries (1, 3, 6):&lt;/strong&gt;']]],
  ['_3a_20syntax_20or_20parse_20errors_5',['&lt;tt&gt;400 Bad Request&lt;/tt&gt;: Syntax or parse errors',['../de/d66/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2docs_2graphql-official_2learn_2debug-errors.html#autotoc_md870',1,'']]],
  ['_3a_20unexpected_20server_20failures_6',['&lt;tt&gt;500 Internal Server Error&lt;/tt&gt;: Unexpected server failures',['../de/d66/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2docs_2graphql-official_2learn_2debug-errors.html#autotoc_md878',1,'']]],
  ['_3a_20void_20tt_7',[': void tt',['..//github/workspace/ecosystem/sdk/resvault-sdk/README.md#autotoc_md2802',1,'&lt;tt&gt;addMessageListener(handler: (event: MessageEvent) =\&gt; void): void&lt;/tt&gt;'],['..//github/workspace/ecosystem/sdk/resvault-sdk/README.md#autotoc_md2803',1,'&lt;tt&gt;removeMessageListener(handler: (event: MessageEvent) =\&gt; void): void&lt;/tt&gt;'],['..//github/workspace/ecosystem/sdk/resvault-sdk/README.md#autotoc_md2801',1,'&lt;tt&gt;sendMessage(message: Message): void&lt;/tt&gt;']]],
  ['_3a_20wrong_20http_20method_8',['&lt;tt&gt;405 Method Not Allowed&lt;/tt&gt;: Wrong HTTP Method',['../de/d66/md__2github_2workspace_2ecosystem_2ai-tools_2mcp_2graphq-llm_2docs_2graphql-official_2learn_2debug-errors.html#autotoc_md874',1,'']]]
];
